apiVersion: v1
kind: Pod
metadata:
  name: test-incluster-client-go
spec:
  containers:
  - name: incluster
    image: in-cluster:latest
    imagePullPolicy: IfNotPresent
    command: ["/bin/sh", "-c", "sleep 60m"]