apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: main-ingress-test
  annotations:
    kubernetes.io/ingress.class: "nginx"   
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
      paths:       
      - path: /hello
        pathType: Prefix
        backend:
          service:
            name: main-ing-svc
            port:
              number: 8083