apiVersion: v1
kind: Service
metadata:
  labels:
    app: etcd
  name: etcd
spec:
  clusterIP: None
  ipFamilyPolicy: SingleStack
  ports:
  - name: etcd-server
    port: 2380
    protocol: TCP
    targetPort: 2380
  - name: etcd-client
    port: 2379
    protocol: TCP
    targetPort: 2379
  publishNotReadyAddresses: true
  selector:
    app: etcd
  sessionAffinity: None
